name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Replace with the version your project uses
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Build the project (optional)
      - name: Build project
        run: npm run build

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test-and-build  # Wait for the test-and-build job to complete

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to server
      - name: Deploy to production
        run: |
          ssh user@your-server.com "
            cd /path/to/your/app &&
            git pull origin main &&
            npm ci &&
            npm run build &&
            pm2 restart app
          "